version: '{branch}-{build}'
build: off
environment:
{%- set environment_global_interior %}
{%- if cookiecutter.c_extension_test_pypi == 'yes' %}
    TWINE_USERNAME: {{ cookiecutter.c_extension_test_pypi_username }}
{%- endif %}
{%- if cookiecutter.coveralls == 'yes' %}
    COVERALLS_EXTRAS: '-v'
{%- if cookiecutter.coveralls_token.strip() not in '-' %}
    COVERALLS_REPO_TOKEN: {{ cookiecutter.coveralls_token }}
{%- endif %}
{%- endif %}
{%- endset %}
{%- if environment_global_interior %}
  global:{{ environment_global_interior }}
{%- endif %}
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
{% if cookiecutter.test_matrix_configurator == "yes" -%}
{{ "{% for env, config in tox_environments|dictsort %}" }}
{%- else -%}
{{ "{% for env in tox_environments %}" }}
{%- endif %}
{{ "{% if env.startswith(('py2', 'py3')) %}" }}
{%- for arch in ['32', '64'] %}
    - TOXENV: {{ "{{ env }}" }}
        {%- if cookiecutter.test_matrix_separate_coverage == "yes" -%}
            {%- if cookiecutter.test_matrix_configurator == "yes" -%}
                {{ "{% if config.cover %}" }}
            {%- else -%}
                {{ "{% if env.endswith('-cover') %}" }}
            {%- endif -%}
        {%- endif -%}
        {%- if cookiecutter.codecov == 'yes' %},codecov{% endif -%}
        {%- if cookiecutter.coveralls == 'yes' %},coveralls{% endif -%}
        {%- if cookiecutter.test_matrix_separate_coverage == "yes" -%}
            {{ "{% endif %}" }}
        {%- endif -%}{{ '{{ "" }}' }}
      TOXPYTHON: C:\Python{{ "{{ env[2:4] }}" }}{{ '' if arch == '32' else '-x64' }}\python.exe
      PYTHON_HOME: C:\Python{{ "{{ env[2:4] }}" }}{{ '' if arch == '32' else '-x64' }}
      PYTHON_VERSION: {{ "'{{ env[2] }}.{{ env[3] }}'"}}
      PYTHON_ARCH: '{{ arch }}'
{{ "{% if 'nocov' in env %}" }}
{{ "      WHEEL_PATH: .tox/dist" }}
{{ "{% endif %}" }}
{%- if arch == '64' %}
{{ "{% if env.startswith('py2') %}" }}
{{ "      WINDOWS_SDK_VERSION: v7.0" }}
{{ "{% endif %}" }}
{%- endif %}
{%- endfor %}
{{ "{% endif %}{% endfor %}" }}
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
{%- if cookiecutter.c_extension_test_pypi == "yes" %}
  - '%PYTHON_HOME%\python -m pip install --progress-bar=off twine tox-wheel -rci/requirements.txt'
{%- else %}
  - '%PYTHON_HOME%\python -m pip install --progress-bar=off tox -rci/requirements.txt'
{%- endif %}
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd %PYTHON_HOME%\Scripts\tox
{%- if cookiecutter.c_extension_test_pypi == "yes" %}
on_success:
  - IF DEFINED WHEEL_PATH %PYTHON_HOME%\Scripts\twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing %WHEEL_PATH%/*.whl
{%- endif %}
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
