language: python
dist: trusty
python: 3.6
group: deprecated-2017Q2
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=matrix-sepcov-pytest-cext-plain-flake8-github
    - ENV=matrix-single-pytest-cext-plain-flake8-github
    - ENV=plain-sepcov-nose-pure-plain-flake8-github
    - ENV=plain-sepcov-pytest-cext-optional-plain-flake8-github
    - ENV=plain-sepcov-pytest-cext-plain-flake8-github
    - ENV=plain-sepcov-pytest-cext-plain-flake8-scm-github-osx-publish
    - ENV=plain-sepcov-pytest-cffi-plain-flake8-github
    - ENV=plain-sepcov-pytest-cffi-plain-flake8-scm-github-osx-publish
    - ENV=plain-sepcov-pytest-cython-plain-flake8-github
    - ENV=plain-sepcov-pytest-cython-plain-flake8-scm-github-osx-publish
    - ENV=plain-sepcov-pytest-pure-plain-flake8-github
    - ENV=plain-single-nose-pure-argparse-flake8-github
    - ENV=plain-single-nose-pure-click-flake8-github
    - ENV=plain-single-nose-pure-nocli-flake8-github
    - ENV=plain-single-nose-pure-plain-flake8-github
    - ENV=plain-single-pytest-cext-optional-plain-flake8-github
    - ENV=plain-single-pytest-cext-plain-flake8-github
    - ENV=plain-single-pytest-cffi-plain-flake8-github
    - ENV=plain-single-pytest-cython-plain-flake8-github
    - ENV=plain-single-pytest-pure-argparse-flake8-github
    - ENV=plain-single-pytest-pure-click-flake8-github
    - ENV=plain-single-pytest-pure-nocli-flake8-github
    - ENV=plain-single-pytest-pure-plain-flake8-github
    - ENV=plain-single-pytest-pure-plain-flake8-private
    - ENV=plain-single-pytest-pure-plain-pylama-github
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - git --version
  - ci/test.sh $ENV
  - |
    set -x
    cd python-nameless
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      PR="pr${TRAVIS_PULL_REQUEST}-"
    else
      PR=""
    fi
    git diff
    set +x
  - |
    if openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in publish-key.enc -out ~/.ssh/publish-key -d; then
      chmod u=rw,og= ~/.ssh/publish-key
      echo "Host github.com" >> ~/.ssh/config
      echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
      # ci/test.sh mangles tox.ini a bit for testing, so we need to undo that.
      git reset --hard
      bumpversion --new-version=1.$TRAVIS_JOB_NUMBER minor
      git push git@github.com:ionelmc/python-nameless.git -f HEAD:${PR}test-$ENV
    else
      echo Failed to get publish-key
      tox --sitepackages
    fi
  - echo Done.

notifications:
  email:
    on_success: never
    on_failure: always
