language: python
dist: trusty
python: 3.6
group: deprecated-2017Q2
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=matrix-nose-argparse-py3doc-flake8
    - ENV=matrix-nose-click-py3doc-flake8
    - ENV=matrix-nose-nocli-py3doc-flake8
    - ENV=matrix-nose-nocli-rtd-flake8
    - ENV=matrix-nose-plain-py3doc-flake8
    - ENV=matrix-pytest-argparse-py3doc-flake8
    - ENV=matrix-pytest-cext-nocli-py3doc-flake8
    - ENV=matrix-pytest-cext-nocli-rtd-flake8
    - ENV=matrix-pytest-cext-optional-nocli-py3doc-flake8
    - ENV=matrix-pytest-cext-optional-nocli-rtd-flake8
    - ENV=matrix-pytest-cffi-nocli-py3doc-flake8
    - ENV=matrix-pytest-cffi-nocli-rtd-flake8
    - ENV=matrix-pytest-click-py3doc-flake8
    - ENV=matrix-pytest-cython-nocli-py3doc-flake8
    - ENV=matrix-pytest-cython-nocli-rtd-flake8
    - ENV=matrix-pytest-nocli-py3doc-flake8
    - ENV=matrix-pytest-nocli-rtd-flake8
    - ENV=matrix-pytest-plain-py3doc-flake8
    - ENV=matrix-separatecover-nose-argparse-py3doc-flake8
    - ENV=matrix-separatecover-nose-click-py3doc-flake8
    - ENV=matrix-separatecover-nose-nocli-py3doc-flake8
    - ENV=matrix-separatecover-nose-nocli-rtd-flake8
    - ENV=matrix-separatecover-nose-plain-py3doc-flake8
    - ENV=matrix-separatecover-pytest-argparse-py3doc-flake8
    - ENV=matrix-separatecover-pytest-cext-nocli-py3doc-flake8
    - ENV=matrix-separatecover-pytest-cext-nocli-rtd-flake8
    - ENV=matrix-separatecover-pytest-cext-optional-nocli-py3doc-flake8
    - ENV=matrix-separatecover-pytest-cext-optional-nocli-rtd-flake8
    - ENV=matrix-separatecover-pytest-cffi-nocli-py3doc-flake8
    - ENV=matrix-separatecover-pytest-cffi-nocli-rtd-flake8
    - ENV=matrix-separatecover-pytest-click-py3doc-flake8
    - ENV=matrix-separatecover-pytest-cython-nocli-py3doc-flake8
    - ENV=matrix-separatecover-pytest-cython-nocli-rtd-flake8
    - ENV=matrix-separatecover-pytest-nocli-py3doc-flake8
    - ENV=matrix-separatecover-pytest-nocli-rtd-flake8
    - ENV=matrix-separatecover-pytest-plain-py3doc-flake8
    - ENV=plain-nose-argparse-py3doc-flake8
    - ENV=plain-nose-click-py3doc-flake8
    - ENV=plain-nose-nocli-py3doc-flake8
    - ENV=plain-nose-nocli-rtd-flake8
    - ENV=plain-nose-plain-py3doc-flake8
    - ENV=plain-pytest-argparse-py3doc-flake8
    - ENV=plain-pytest-argparse-py3doc-pylama
    - ENV=plain-pytest-cext-nocli-py3doc-flake8
    - ENV=plain-pytest-cext-nocli-py3doc-pylama
    - ENV=plain-pytest-cext-nocli-rtd-flake8
    - ENV=plain-pytest-cext-nocli-rtd-pylama
    - ENV=plain-pytest-cext-optional-nocli-py3doc-flake8
    - ENV=plain-pytest-cext-optional-nocli-py3doc-pylama
    - ENV=plain-pytest-cext-optional-nocli-rtd-flake8
    - ENV=plain-pytest-cext-optional-nocli-rtd-pylama
    - ENV=plain-pytest-cffi-nocli-py3doc-flake8
    - ENV=plain-pytest-cffi-nocli-py3doc-pylama
    - ENV=plain-pytest-cffi-nocli-rtd-flake8
    - ENV=plain-pytest-cffi-nocli-rtd-pylama
    - ENV=plain-pytest-click-py3doc-flake8
    - ENV=plain-pytest-click-py3doc-pylama
    - ENV=plain-pytest-cython-nocli-py3doc-flake8
    - ENV=plain-pytest-cython-nocli-py3doc-pylama
    - ENV=plain-pytest-cython-nocli-rtd-flake8
    - ENV=plain-pytest-cython-nocli-rtd-pylama
    - ENV=plain-pytest-nocli-py3doc-flake8
    - ENV=plain-pytest-nocli-py3doc-pylama
    - ENV=plain-pytest-nocli-rtd-flake8
    - ENV=plain-pytest-nocli-rtd-pylama
    - ENV=plain-pytest-plain-py3doc-flake8
    - ENV=plain-pytest-plain-py3doc-pylama
    - ENV=plain-separatecover-nose-argparse-py3doc-flake8
    - ENV=plain-separatecover-nose-click-py3doc-flake8
    - ENV=plain-separatecover-nose-nocli-py3doc-flake8
    - ENV=plain-separatecover-nose-nocli-rtd-flake8
    - ENV=plain-separatecover-nose-plain-py3doc-flake8
    - ENV=plain-separatecover-pytest-argparse-py3doc-flake8
    - ENV=plain-separatecover-pytest-cext-nocli-py3doc-flake8
    - ENV=plain-separatecover-pytest-cext-nocli-rtd-flake8
    - ENV=plain-separatecover-pytest-cext-optional-nocli-py3doc-flake8
    - ENV=plain-separatecover-pytest-cext-optional-nocli-rtd-flake8
    - ENV=plain-separatecover-pytest-cffi-nocli-py3doc-flake8
    - ENV=plain-separatecover-pytest-cffi-nocli-rtd-flake8
    - ENV=plain-separatecover-pytest-click-py3doc-flake8
    - ENV=plain-separatecover-pytest-cython-nocli-py3doc-flake8
    - ENV=plain-separatecover-pytest-cython-nocli-rtd-flake8
    - ENV=plain-separatecover-pytest-nocli-py3doc-flake8
    - ENV=plain-separatecover-pytest-nocli-rtd-flake8
    - ENV=plain-separatecover-pytest-plain-py3doc-flake8
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
