language: python
dist: xenial
python: '3.7'
cache:
  directories:
    - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - ENV=cext
    - ENV=cffi
    - ENV=cython
    - ENV=matrix-cext
    - ENV=matrix-separate-cext
    - ENV=nose-pure
    - ENV=nose-pure-argparse
    - ENV=nose-pure-click
    - ENV=nose-pure-nocli
    - ENV=pure
    - ENV=pure-argparse
    - ENV=pure-click
    - ENV=pure-nocli
    - ENV=pure-private
    - ENV=pure-pylama
    - ENV=separate-cext
    - ENV=separate-cext-scm-osx-publish
    - ENV=separate-cffi
    - ENV=separate-cffi-scm-osx-publish
    - ENV=separate-cython
    - ENV=separate-cython-scm-osx-publish
    - ENV=separate-nose-pure
    - ENV=separate-pure
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools tox cookiecutter bumpversion
  - virtualenv --version
  - tox --version
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - git --version
  - ci/test.sh $ENV
  - cd python-nameless
  - git diff
  - |
    set -x
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      PR="pr${TRAVIS_PULL_REQUEST}-"
    else
      PR=""
    fi
    set +x
  - |
    if openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in ../publish-key.enc -out ~/.ssh/publish-key -d; then
      chmod u=rw,og= ~/.ssh/publish-key
      echo "Host github.com" >> ~/.ssh/config
      echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
      # ci/test.sh mangles tox.ini a bit for testing, so we need to undo that.
      git reset --hard
      bumpversion --new-version=1.$TRAVIS_JOB_NUMBER minor
      git push git@github.com:ionelmc/python-nameless.git -f HEAD:${PR}test-$ENV
    else
      echo Failed to get publish-key
      mkdir -p ~/.local/bin
      for name in pypy pypy3; do
        curl -sSf -o $name.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/16.04/x86_64/$name.tar.bz2
        tar xjf $name.tar.bz2 --directory /
        rm $name.tar.bz2
        ln -s /opt/python/$name/bin/$name ~/.local/bin/$name
      done
      tox --sitepackages
    fi
  - echo Done.

notifications:
  email:
    on_success: never
    on_failure: always
