build: off
version: '{branch}-{build}'
cache: C:\Users\appveyor\pip\wheels
matrix:
  fast_finish: true
environment:
  matrix:
    - ENV: matrix-nose-cext-cython-fndef-pndef-click-no
    - ENV: matrix-nose-cext-cython-fndef-pndef-click-yes
    - ENV: matrix-nose-cext-cython-fndef-pndef-no-no
    - ENV: matrix-nose-cext-cython-fndef-pndef-no-yes
    - ENV: matrix-nose-cext-cython-fndef-pndef-plain-no
    - ENV: matrix-nose-cext-cython-fndef-pndef-plain-yes
    - ENV: matrix-nose-cext-fndef-pndef-click-no
    - ENV: matrix-nose-cext-fndef-pndef-click-yes
    - ENV: matrix-nose-cext-fndef-pndef-no-no
    - ENV: matrix-nose-cext-fndef-pndef-no-yes
    - ENV: matrix-nose-cext-fndef-pndef-plain-no
    - ENV: matrix-nose-cext-fndef-pndef-plain-yes
    - ENV: matrix-nose-cext-optional-cython-fndef-pndef-click-no
    - ENV: matrix-nose-cext-optional-cython-fndef-pndef-click-yes
    - ENV: matrix-nose-cext-optional-cython-fndef-pndef-no-no
    - ENV: matrix-nose-cext-optional-cython-fndef-pndef-no-yes
    - ENV: matrix-nose-cext-optional-cython-fndef-pndef-plain-no
    - ENV: matrix-nose-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: matrix-nose-cext-optional-fndef-pndef-click-no
    - ENV: matrix-nose-cext-optional-fndef-pndef-click-yes
    - ENV: matrix-nose-cext-optional-fndef-pndef-no-no
    - ENV: matrix-nose-cext-optional-fndef-pndef-no-yes
    - ENV: matrix-nose-cext-optional-fndef-pndef-plain-no
    - ENV: matrix-nose-cext-optional-fndef-pndef-plain-yes
    - ENV: matrix-nose-fndef-pndef-click-no
    - ENV: matrix-nose-fndef-pndef-click-yes
    - ENV: matrix-nose-fndef-pndef-no-no
    - ENV: matrix-nose-fndef-pndef-no-yes
    - ENV: matrix-nose-fndef-pndef-plain-no
    - ENV: matrix-nose-fndef-pndef-plain-yes
    - ENV: matrix-pytest-cext-cython-fndef-pndef-click-no
    - ENV: matrix-pytest-cext-cython-fndef-pndef-click-yes
    - ENV: matrix-pytest-cext-cython-fndef-pndef-no-no
    - ENV: matrix-pytest-cext-cython-fndef-pndef-no-yes
    - ENV: matrix-pytest-cext-cython-fndef-pndef-plain-no
    - ENV: matrix-pytest-cext-cython-fndef-pndef-plain-yes
    - ENV: matrix-pytest-cext-fndef-pndef-click-no
    - ENV: matrix-pytest-cext-fndef-pndef-click-yes
    - ENV: matrix-pytest-cext-fndef-pndef-no-no
    - ENV: matrix-pytest-cext-fndef-pndef-no-yes
    - ENV: matrix-pytest-cext-fndef-pndef-plain-no
    - ENV: matrix-pytest-cext-fndef-pndef-plain-yes
    - ENV: matrix-pytest-cext-optional-cython-fndef-pndef-click-no
    - ENV: matrix-pytest-cext-optional-cython-fndef-pndef-click-yes
    - ENV: matrix-pytest-cext-optional-cython-fndef-pndef-no-no
    - ENV: matrix-pytest-cext-optional-cython-fndef-pndef-no-yes
    - ENV: matrix-pytest-cext-optional-cython-fndef-pndef-plain-no
    - ENV: matrix-pytest-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: matrix-pytest-cext-optional-fndef-pndef-click-no
    - ENV: matrix-pytest-cext-optional-fndef-pndef-click-yes
    - ENV: matrix-pytest-cext-optional-fndef-pndef-no-no
    - ENV: matrix-pytest-cext-optional-fndef-pndef-no-yes
    - ENV: matrix-pytest-cext-optional-fndef-pndef-plain-no
    - ENV: matrix-pytest-cext-optional-fndef-pndef-plain-yes
    - ENV: matrix-pytest-fndef-pndef-click-no
    - ENV: matrix-pytest-fndef-pndef-click-yes
    - ENV: matrix-pytest-fndef-pndef-no-no
    - ENV: matrix-pytest-fndef-pndef-no-yes
    - ENV: matrix-pytest-fndef-pndef-plain-no
    - ENV: matrix-pytest-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-nose-cext-cython-fndef-pndef-click-no
    - ENV: matrix-separatecover-nose-cext-cython-fndef-pndef-click-yes
    - ENV: matrix-separatecover-nose-cext-cython-fndef-pndef-no-no
    - ENV: matrix-separatecover-nose-cext-cython-fndef-pndef-no-yes
    - ENV: matrix-separatecover-nose-cext-cython-fndef-pndef-plain-no
    - ENV: matrix-separatecover-nose-cext-cython-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-nose-cext-fndef-pndef-click-no
    - ENV: matrix-separatecover-nose-cext-fndef-pndef-click-yes
    - ENV: matrix-separatecover-nose-cext-fndef-pndef-no-no
    - ENV: matrix-separatecover-nose-cext-fndef-pndef-no-yes
    - ENV: matrix-separatecover-nose-cext-fndef-pndef-plain-no
    - ENV: matrix-separatecover-nose-cext-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-nose-cext-optional-cython-fndef-pndef-click-no
    - ENV: matrix-separatecover-nose-cext-optional-cython-fndef-pndef-click-yes
    - ENV: matrix-separatecover-nose-cext-optional-cython-fndef-pndef-no-no
    - ENV: matrix-separatecover-nose-cext-optional-cython-fndef-pndef-no-yes
    - ENV: matrix-separatecover-nose-cext-optional-cython-fndef-pndef-plain-no
    - ENV: matrix-separatecover-nose-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-nose-cext-optional-fndef-pndef-click-no
    - ENV: matrix-separatecover-nose-cext-optional-fndef-pndef-click-yes
    - ENV: matrix-separatecover-nose-cext-optional-fndef-pndef-no-no
    - ENV: matrix-separatecover-nose-cext-optional-fndef-pndef-no-yes
    - ENV: matrix-separatecover-nose-cext-optional-fndef-pndef-plain-no
    - ENV: matrix-separatecover-nose-cext-optional-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-nose-fndef-pndef-click-no
    - ENV: matrix-separatecover-nose-fndef-pndef-click-yes
    - ENV: matrix-separatecover-nose-fndef-pndef-no-no
    - ENV: matrix-separatecover-nose-fndef-pndef-no-yes
    - ENV: matrix-separatecover-nose-fndef-pndef-plain-no
    - ENV: matrix-separatecover-nose-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-pytest-cext-cython-fndef-pndef-click-no
    - ENV: matrix-separatecover-pytest-cext-cython-fndef-pndef-click-yes
    - ENV: matrix-separatecover-pytest-cext-cython-fndef-pndef-no-no
    - ENV: matrix-separatecover-pytest-cext-cython-fndef-pndef-no-yes
    - ENV: matrix-separatecover-pytest-cext-cython-fndef-pndef-plain-no
    - ENV: matrix-separatecover-pytest-cext-cython-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-pytest-cext-fndef-pndef-click-no
    - ENV: matrix-separatecover-pytest-cext-fndef-pndef-click-yes
    - ENV: matrix-separatecover-pytest-cext-fndef-pndef-no-no
    - ENV: matrix-separatecover-pytest-cext-fndef-pndef-no-yes
    - ENV: matrix-separatecover-pytest-cext-fndef-pndef-plain-no
    - ENV: matrix-separatecover-pytest-cext-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-pytest-cext-optional-cython-fndef-pndef-click-no
    - ENV: matrix-separatecover-pytest-cext-optional-cython-fndef-pndef-click-yes
    - ENV: matrix-separatecover-pytest-cext-optional-cython-fndef-pndef-no-no
    - ENV: matrix-separatecover-pytest-cext-optional-cython-fndef-pndef-no-yes
    - ENV: matrix-separatecover-pytest-cext-optional-cython-fndef-pndef-plain-no
    - ENV: matrix-separatecover-pytest-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-pytest-cext-optional-fndef-pndef-click-no
    - ENV: matrix-separatecover-pytest-cext-optional-fndef-pndef-click-yes
    - ENV: matrix-separatecover-pytest-cext-optional-fndef-pndef-no-no
    - ENV: matrix-separatecover-pytest-cext-optional-fndef-pndef-no-yes
    - ENV: matrix-separatecover-pytest-cext-optional-fndef-pndef-plain-no
    - ENV: matrix-separatecover-pytest-cext-optional-fndef-pndef-plain-yes
    - ENV: matrix-separatecover-pytest-fndef-pndef-click-no
    - ENV: matrix-separatecover-pytest-fndef-pndef-click-yes
    - ENV: matrix-separatecover-pytest-fndef-pndef-no-no
    - ENV: matrix-separatecover-pytest-fndef-pndef-no-yes
    - ENV: matrix-separatecover-pytest-fndef-pndef-plain-no
    - ENV: matrix-separatecover-pytest-fndef-pndef-plain-yes
    - ENV: plain-nose-cext-cython-fndef-pndef-click-no
    - ENV: plain-nose-cext-cython-fndef-pndef-click-yes
    - ENV: plain-nose-cext-cython-fndef-pndef-no-no
    - ENV: plain-nose-cext-cython-fndef-pndef-no-yes
    - ENV: plain-nose-cext-cython-fndef-pndef-plain-no
    - ENV: plain-nose-cext-cython-fndef-pndef-plain-yes
    - ENV: plain-nose-cext-fndef-pndef-click-no
    - ENV: plain-nose-cext-fndef-pndef-click-yes
    - ENV: plain-nose-cext-fndef-pndef-no-no
    - ENV: plain-nose-cext-fndef-pndef-no-yes
    - ENV: plain-nose-cext-fndef-pndef-plain-no
    - ENV: plain-nose-cext-fndef-pndef-plain-yes
    - ENV: plain-nose-cext-optional-cython-fndef-pndef-click-no
    - ENV: plain-nose-cext-optional-cython-fndef-pndef-click-yes
    - ENV: plain-nose-cext-optional-cython-fndef-pndef-no-no
    - ENV: plain-nose-cext-optional-cython-fndef-pndef-no-yes
    - ENV: plain-nose-cext-optional-cython-fndef-pndef-plain-no
    - ENV: plain-nose-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: plain-nose-cext-optional-fndef-pndef-click-no
    - ENV: plain-nose-cext-optional-fndef-pndef-click-yes
    - ENV: plain-nose-cext-optional-fndef-pndef-no-no
    - ENV: plain-nose-cext-optional-fndef-pndef-no-yes
    - ENV: plain-nose-cext-optional-fndef-pndef-plain-no
    - ENV: plain-nose-cext-optional-fndef-pndef-plain-yes
    - ENV: plain-nose-fndef-pndef-click-no
    - ENV: plain-nose-fndef-pndef-click-yes
    - ENV: plain-nose-fndef-pndef-no-no
    - ENV: plain-nose-fndef-pndef-no-yes
    - ENV: plain-nose-fndef-pndef-plain-no
    - ENV: plain-nose-fndef-pndef-plain-yes
    - ENV: plain-pytest-cext-cython-fndef-pndef-click-no
    - ENV: plain-pytest-cext-cython-fndef-pndef-click-yes
    - ENV: plain-pytest-cext-cython-fndef-pndef-no-no
    - ENV: plain-pytest-cext-cython-fndef-pndef-no-yes
    - ENV: plain-pytest-cext-cython-fndef-pndef-plain-no
    - ENV: plain-pytest-cext-cython-fndef-pndef-plain-yes
    - ENV: plain-pytest-cext-fndef-pndef-click-no
    - ENV: plain-pytest-cext-fndef-pndef-click-yes
    - ENV: plain-pytest-cext-fndef-pndef-no-no
    - ENV: plain-pytest-cext-fndef-pndef-no-yes
    - ENV: plain-pytest-cext-fndef-pndef-plain-no
    - ENV: plain-pytest-cext-fndef-pndef-plain-yes
    - ENV: plain-pytest-cext-optional-cython-fndef-pndef-click-no
    - ENV: plain-pytest-cext-optional-cython-fndef-pndef-click-yes
    - ENV: plain-pytest-cext-optional-cython-fndef-pndef-no-no
    - ENV: plain-pytest-cext-optional-cython-fndef-pndef-no-yes
    - ENV: plain-pytest-cext-optional-cython-fndef-pndef-plain-no
    - ENV: plain-pytest-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: plain-pytest-cext-optional-fndef-pndef-click-no
    - ENV: plain-pytest-cext-optional-fndef-pndef-click-yes
    - ENV: plain-pytest-cext-optional-fndef-pndef-no-no
    - ENV: plain-pytest-cext-optional-fndef-pndef-no-yes
    - ENV: plain-pytest-cext-optional-fndef-pndef-plain-no
    - ENV: plain-pytest-cext-optional-fndef-pndef-plain-yes
    - ENV: plain-pytest-fnaccents-pnaccents-no-no
    - ENV: plain-pytest-fnaccents-pnaccents-no-yes
    - ENV: plain-pytest-fndef-pndef-click-no
    - ENV: plain-pytest-fndef-pndef-click-yes
    - ENV: plain-pytest-fndef-pndef-no-no
    - ENV: plain-pytest-fndef-pndef-no-yes
    - ENV: plain-pytest-fndef-pndef-plain-no
    - ENV: plain-pytest-fndef-pndef-plain-yes
    - ENV: plain-pytest-fndef-pnquotes-no-no
    - ENV: plain-pytest-fndef-pnquotes-no-yes
    - ENV: plain-pytest-fnquotes-pndef-no-no
    - ENV: plain-pytest-fnquotes-pndef-no-yes
    - ENV: plain-pytest-fnquotes-pnquotes-no-no
    - ENV: plain-pytest-fnquotes-pnquotes-no-yes
    - ENV: plain-separatecover-nose-cext-cython-fndef-pndef-click-no
    - ENV: plain-separatecover-nose-cext-cython-fndef-pndef-click-yes
    - ENV: plain-separatecover-nose-cext-cython-fndef-pndef-no-no
    - ENV: plain-separatecover-nose-cext-cython-fndef-pndef-no-yes
    - ENV: plain-separatecover-nose-cext-cython-fndef-pndef-plain-no
    - ENV: plain-separatecover-nose-cext-cython-fndef-pndef-plain-yes
    - ENV: plain-separatecover-nose-cext-fndef-pndef-click-no
    - ENV: plain-separatecover-nose-cext-fndef-pndef-click-yes
    - ENV: plain-separatecover-nose-cext-fndef-pndef-no-no
    - ENV: plain-separatecover-nose-cext-fndef-pndef-no-yes
    - ENV: plain-separatecover-nose-cext-fndef-pndef-plain-no
    - ENV: plain-separatecover-nose-cext-fndef-pndef-plain-yes
    - ENV: plain-separatecover-nose-cext-optional-cython-fndef-pndef-click-no
    - ENV: plain-separatecover-nose-cext-optional-cython-fndef-pndef-click-yes
    - ENV: plain-separatecover-nose-cext-optional-cython-fndef-pndef-no-no
    - ENV: plain-separatecover-nose-cext-optional-cython-fndef-pndef-no-yes
    - ENV: plain-separatecover-nose-cext-optional-cython-fndef-pndef-plain-no
    - ENV: plain-separatecover-nose-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: plain-separatecover-nose-cext-optional-fndef-pndef-click-no
    - ENV: plain-separatecover-nose-cext-optional-fndef-pndef-click-yes
    - ENV: plain-separatecover-nose-cext-optional-fndef-pndef-no-no
    - ENV: plain-separatecover-nose-cext-optional-fndef-pndef-no-yes
    - ENV: plain-separatecover-nose-cext-optional-fndef-pndef-plain-no
    - ENV: plain-separatecover-nose-cext-optional-fndef-pndef-plain-yes
    - ENV: plain-separatecover-nose-fndef-pndef-click-no
    - ENV: plain-separatecover-nose-fndef-pndef-click-yes
    - ENV: plain-separatecover-nose-fndef-pndef-no-no
    - ENV: plain-separatecover-nose-fndef-pndef-no-yes
    - ENV: plain-separatecover-nose-fndef-pndef-plain-no
    - ENV: plain-separatecover-nose-fndef-pndef-plain-yes
    - ENV: plain-separatecover-pytest-cext-cython-fndef-pndef-click-no
    - ENV: plain-separatecover-pytest-cext-cython-fndef-pndef-click-yes
    - ENV: plain-separatecover-pytest-cext-cython-fndef-pndef-no-no
    - ENV: plain-separatecover-pytest-cext-cython-fndef-pndef-no-yes
    - ENV: plain-separatecover-pytest-cext-cython-fndef-pndef-plain-no
    - ENV: plain-separatecover-pytest-cext-cython-fndef-pndef-plain-yes
    - ENV: plain-separatecover-pytest-cext-fndef-pndef-click-no
    - ENV: plain-separatecover-pytest-cext-fndef-pndef-click-yes
    - ENV: plain-separatecover-pytest-cext-fndef-pndef-no-no
    - ENV: plain-separatecover-pytest-cext-fndef-pndef-no-yes
    - ENV: plain-separatecover-pytest-cext-fndef-pndef-plain-no
    - ENV: plain-separatecover-pytest-cext-fndef-pndef-plain-yes
    - ENV: plain-separatecover-pytest-cext-optional-cython-fndef-pndef-click-no
    - ENV: plain-separatecover-pytest-cext-optional-cython-fndef-pndef-click-yes
    - ENV: plain-separatecover-pytest-cext-optional-cython-fndef-pndef-no-no
    - ENV: plain-separatecover-pytest-cext-optional-cython-fndef-pndef-no-yes
    - ENV: plain-separatecover-pytest-cext-optional-cython-fndef-pndef-plain-no
    - ENV: plain-separatecover-pytest-cext-optional-cython-fndef-pndef-plain-yes
    - ENV: plain-separatecover-pytest-cext-optional-fndef-pndef-click-no
    - ENV: plain-separatecover-pytest-cext-optional-fndef-pndef-click-yes
    - ENV: plain-separatecover-pytest-cext-optional-fndef-pndef-no-no
    - ENV: plain-separatecover-pytest-cext-optional-fndef-pndef-no-yes
    - ENV: plain-separatecover-pytest-cext-optional-fndef-pndef-plain-no
    - ENV: plain-separatecover-pytest-cext-optional-fndef-pndef-plain-yes
    - ENV: plain-separatecover-pytest-fndef-pndef-click-no
    - ENV: plain-separatecover-pytest-fndef-pndef-click-yes
    - ENV: plain-separatecover-pytest-fndef-pndef-no-no
    - ENV: plain-separatecover-pytest-fndef-pndef-no-yes
    - ENV: plain-separatecover-pytest-fndef-pndef-plain-no
    - ENV: plain-separatecover-pytest-fndef-pndef-plain-yes
init:
  - "echo %CTX%"
  - "set"
  - ps: "ls C:\\Python*"
install:
  - ps: if (Test-Path c:/Users/appveyor/pip/wheels) { ls c:/Users/appveyor/pip/wheels } else { echo Wheelhouse missing. }
  - ps: New-Item -Force -ItemType directory -Path "c:/Users/appveyor/pip/wheels"
  - ps: ls c:/Users/appveyor/pip/wheels
  - ps: Copy-Item -Path "./ci/pip.ini" -Destination "c:/Users/appveyor/pip/pip.ini" -Force
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:\\ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:\\get-pip.py"
  - "c:\\python27\\python c:\\get-pip.py setuptools"
  - "c:\\python27\\Scripts\\pip wheel tox virtualenv cookiecutter bumpversion"
  - "c:\\python27\\Scripts\\pip wheel pytest-capturelog pytest-cov pytest"
  - "c:\\python27\\Scripts\\pip wheel nose coverage"
  - "c:\\python27\\Scripts\\pip wheel cpp-coveralls"
  - "c:\\python27\\Scripts\\pip wheel jinja2 matrix"
  - "c:\\python27\\Scripts\\pip wheel docutils check-manifest flake8 readme-renderer pygments"
  - "c:\\python27\\Scripts\\pip install -I -U --index-url https://pypi.anaconda.org/ionelmc/simple virtualenv"
  - "c:\\python27\\Scripts\\pip install -I -U tox cookiecutter"
test_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - powershell ci\\test.ps1 $Env:ENV
