{% raw -%}
name: build
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: {{ '${{ matrix.name }}' }}
    runs-on: {{ '${{ matrix.os }}' }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.11'
            toxpython: 'python3.11'
            tox_env: 'check'
            os: 'ubuntu-latest'
{%- endraw %}
{%- if cookiecutter.sphinx_docs == "yes" %}
          - name: 'docs'
            python: '3.11'
            toxpython: 'python3.11'
            tox_env: 'docs'
            os: 'ubuntu-latest'
{%- endif %}
{%- raw %}
{% for env in tox_environments %}
{% set prefix = env.split('-')[0] -%}
{% if prefix.startswith('pypy') %}
{% set python %}pypy-{{ prefix[4] }}.{{ prefix[5:] }}{% endset %}
{% set cpython %}pp{{ prefix[4:5] }}{% endset %}
{% set toxpython %}pypy{{ prefix[4] }}.{{ prefix[5:] }}{% endset %}
{% else %}
{% set python %}{{ prefix[2] }}.{{ prefix[3:] }}{% endset %}
{% set cpython %}cp{{ prefix[2:] }}{% endset %}
{% set toxpython %}python{{ prefix[2] }}.{{ prefix[3:] }}{% endset %}
{% endif %}
{%- endraw %}
{%- if cookiecutter.c_extension_support == 'no' %}
{%- raw %}
{% for os, python_arch in [
    ['ubuntu', 'x64'],
{%- endraw %}
{%- if cookiecutter.github_actions_windows == 'yes' %}
    ['windows', 'x64'],
{%- endif %}
{%- if cookiecutter.github_actions_osx == 'yes' %}
    ['macos', 'x64'],
{%- endif %}
{%- raw %}
] %}
          - name: '{{ env }} ({{ os }})'
            python: '{{ python }}'
            toxpython: '{{ toxpython }}'
            python_arch: '{{ python_arch }}'
            tox_env: '{{ env }}'
            os: '{{ os }}-latest'
{% endfor %}
{% endfor %}
    steps:
{%- endraw %}
{%- else %}
{%- raw %}
{% for os, python_arch, cibw_arch, wheel_arch, include_cover in [
    ['ubuntu', 'x64', 'x86_64', '*manylinux*', True],
    ['ubuntu', 'x64', 'x86_64', '*musllinux*', False],
    ['ubuntu', 'x64', 'aarch64', '*manylinux*', False],
    ['ubuntu', 'x64', 'aarch64', '*musllinux*', False],
    ['windows', 'x64', 'AMD64', '*', True],
    ['windows', 'x86', 'x86', '*', False],
    ['macos', 'x64', 'x86_64', '*', True],
] %}
{% if include_cover or ('nocov' in env and not prefix.startswith('pypy')) %}
{% set wheel_suffix = 'nocov' in env and wheel_arch.strip('*') %}
{% set name_suffix = '/' + wheel_suffix if wheel_suffix else '' %}
          - name: '{{ env }} ({{ os }}/{{ cibw_arch }}{{ name_suffix }})'
            python: '{{ python }}'
            toxpython: '{{ toxpython }}'
            python_arch: '{{ python_arch }}'
            tox_env: '{{ env }}'
{% if 'cover' in env %}
            cover: true
{% endif %}
            cibw_arch: '{{ cibw_arch }}'
{% if 'nocov' in env and not prefix.startswith('pypy') %}
            cibw_build: '{{ cpython }}-{{ wheel_arch }}'
{% else %}
            cibw_build: false
{% endif %}
            os: '{{ os }}-latest'
{% endif %}
{% endfor %}
{% endfor %}
    steps:
    - uses: docker/setup-qemu-action@v3
      if: matrix.cibw_arch == 'aarch64'
      with:
        platforms: arm64
{%- endraw %}
{%- endif %}
{%- raw %}
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: {{ '${{ matrix.python }}' }}
        architecture: {{ '${{ matrix.python_arch }}' }}
{%- endraw %}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off{% if cookiecutter.c_extension_support != 'no' %} cibuildwheel{% endif %} -r ci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
        pip list --format=freeze
{%- if cookiecutter.c_extension_support == 'no' %}
{%- raw %}
    - name: test
      env:
        TOXPYTHON: '{{ '${{ matrix.toxpython }}' }}'
      run: >
        tox -e {{ '${{ matrix.tox_env }}' }} -v
{%- endraw %}
{%- else %}
{%- raw %}
    - name: cibw build and test
      if: matrix.cibw_build
      run: cibuildwheel
      env:
        TOXPYTHON: '{{ '${{ matrix.toxpython }}' }}'
        CIBW_ARCHS: '{{ '${{ matrix.cibw_arch }}' }}'
        CIBW_BUILD: '{{ '${{ matrix.cibw_build }}' }}'
        CIBW_BUILD_VERBOSITY: '3'
        CIBW_TEST_REQUIRES: >
          tox
          tox-direct
        CIBW_TEST_COMMAND: >
          cd {project} &&
          tox --skip-pkg-install --direct-yolo -e {{ '${{ matrix.tox_env }}' }} -v
        CIBW_TEST_COMMAND_WINDOWS: >
          cd /d {project} &&
          tox --skip-pkg-install --direct-yolo -e {{ '${{ matrix.tox_env }}' }} -v
    - name: regular build and test
      env:
        TOXPYTHON: '{{ '${{ matrix.toxpython }}' }}'
      if: >
        !matrix.cibw_build
      run: >
        tox -e {{ '${{ matrix.tox_env }}' }} -v
{%- endraw %}
{%- if cookiecutter.coveralls == 'yes' %}
    - uses: coverallsapp/github-action@v2
      if: matrix.cover
      continue-on-error: true
      with:
        parallel: true
        flag-name: {{ "{{ '${{ matrix.tox_env }}' }}" }}
{%- endif %}
{%- if cookiecutter.codecov == 'yes' %}
    - uses: codecov/codecov-action@v3
      if: matrix.cover
      with:
        verbose: true
        flags: {{ "{{ '${{ matrix.tox_env }}' }}" }}
{%- endif %}
    - name: check wheel
      if: matrix.cibw_build
      run: twine check wheelhouse/*.whl
    - name: upload wheel
      uses: actions/upload-artifact@v3
      if: matrix.cibw_build
      with:
        path: wheelhouse/*.whl
{%- endif %}
{%- if cookiecutter.coveralls == 'yes' %}
  finish:
    needs: test
    if: {{ "{{ '${{ always() }}' }}" }}
    runs-on: ubuntu-latest
    steps:
    - uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
{%- endif %}
