language: python
dist: trusty
python: 3.6
group: deprecated-2017Q2
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
{% for env, config in tox_environments|dictsort %}
    - ENV={{ env }}
{% endfor %}
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - openssl aes-256-cbc -K $encrypted_a70d5afca909_key -iv $encrypted_a70d5afca909_iv -in publish-key.enc -out ~/.ssh/publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
  - git --version
  - ci/test.sh $ENV
  - |
    set -x
    cd python-nameless
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      PR="pr${TRAVIS_PULL_REQUEST}-"
    else
      PR=""
    fi
    git diff
    git reset --hard
    bumpversion --new-version=0.$TRAVIS_JOB_NUMBER minor
    git push git@github.com:ionelmc/python-nameless.git -f HEAD:${PR}test-$ENV
  - echo Done.

notifications:
  email:
    on_success: never
    on_failure: always
