language: python
python:
  - 2.7
  - 3.4
sudo: false
cache:
  directories:
  - $HOME/.pip/wheels
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
{% for env, config in tox_environments|dictsort %}
    - ENV={{ env }}
{% endfor %}
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip wheel tox virtualenv cookiecutter bumpversion
  - pip wheel pytest-capturelog pytest-cov pytest
  - pip wheel nose coverage
  - pip wheel cpp-coveralls
  - pip wheel jinja2 matrix
  - pip wheel docutils check-manifest flake8 readme pygments
  - pip install -I -U tox cookiecutter bumpversion
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ci/test.sh $ENV
notifications:
  email:
    on_success: never
    on_failure: always
