version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: check
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: '2.7{% if cookiecutter.codecov|lower == 'yes' %},codecov{% endif %}'
      TOXPYTHON: C:\Python27\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: '2.7-nocover'
      TOXPYTHON: C:\Python27\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    - TOXENV: '3.4{% if cookiecutter.codecov|lower == 'yes' %},codecov{% endif %}'
      TOXPYTHON: C:\Python34\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\Python34
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '32'
    - TOXENV: '3.4-nocover'
      TOXPYTHON: C:\Python34\python.exe
      WINDOWS_SDK_VERSION: v7.1
      PYTHON_HOME: C:\Python34
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '32'
    - TOXENV: '3.5{% if cookiecutter.codecov|lower == 'yes' %},codecov{% endif %}'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python33
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
    - TOXENV: '3.5-nocover'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'
init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - python -u ci\appveyor-bootstrap.py
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox'
{% if cookiecutter.c_extension_support|lower == 'yes' %}
after_test:
  - IF "%TOXENV:~-8,8%" == "-nocover" %WITH_COMPILER% %TOXPYTHON% setup.py bdist_wheel
{% endif %}
on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*
### To enable remote debugging uncomment this:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
